//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LimitedReleases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LimitedReleases()
        {
            this.Records = new HashSet<Record>();
        }
    
        public int LimitID { get; set; }
        public Nullable<System.DateTime> OriginalReleaseDate { get; set; }
        public Nullable<int> OriginalReleaseAmount { get; set; }
        public Nullable<int> LimitedReleaseAmount { get; set; }
        public Nullable<System.DateTime> LimitedReleaseDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Records { get; set; }
    }
}
