//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public string RecordName { get; set; }
        public string BandMusician { get; set; }
        public Nullable<int> GenreID { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CoverImage { get; set; }
        public int StockID { get; set; }
        public Nullable<int> ProducerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ColoredLP { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual StockStatus StockStatus { get; set; }
    }
}
